### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by JonathanHeyno** [valtterikantanen/ot-harjoitustyo#1]
Tiedostot ladattu 28.4. klo. 17:50

1) Koodi on erittäin selkeää, rakenteellisesti järkevä ja noudattaa hyviä koodauskäytänteitä. Siten ei oikeastaan ole hirveästi kommentoitavaa itse koodin laatuun, pikemminkin ainoastaan ohjelman toiminnallisuuteen ja bugeihin.

Budget_service_test.py tiedoston setUp metodia voisi hieman muokata. Nyt ennen jokaista testiä ajetaan initialize_database() metodi, jonka jälkeen ajetaan build() metodi joka suorittaa uudestaan initialize_database() metodin.
Lisäksi valtaosa testeistä alkaa ajamalla komento:
self.budget_service.create_user("antero", "password123", "password123")

Tämän voisi sisällyttää setUp -metodiin niin ettei sitä tarvitse toistaa erikseen jokaisen testin alussa

2) Kun olen luonut käyttäjän, täytyy ilmeisesti sulkea sovellus ja käynnistää uudelleen että pääsee loggaamaan sisään. Kannattaisi varmaan laittaa loggauksen jälkeen joko login näkymä näkyville, tai sitten lagata käyttäjä samantien sisään, tai laittaa jokin nappula josta pääsee takaisin alkunäkymään. Nyt en keksinyt muuta kuin sammuttaa ohjelman ja käynnistää uudestaan.

3) Ohjelma kirjoittaa terminaaliin kaikki ilmoitukset jotka ajon aikana syntyy. Jatkokehitysideana kannattaisi laitta ko. ilmoitukset näkyviin graafiseen käyttöliittymään, koska käyttäjä ei välttämättä katsele terminaalia.

4) Kun lisää uuden menon ilman kategoriaa, ohjelma heittää virheen ja tulostaa terminaaliin tracebackin
 
5) Kun lisää uuden tulon ilman kategoriaa, terminaali väittää että tulo on lisätty, vaikka ilmeisesti todellisuudessa ei ole

6) Graafisessa käyttöliittymässä ei voi lisätä ja poistaa kategorioita. Toimii tekstikäyttöliittymässä.

7) Kun käyttäjä poistaa kategorian, se poistetaan kaikilta käyttäjiltä. Ts. jokin käyttäjä voi poistaa kaikki, myös muiden tekemät kategoriat tietokannasta. Ja sitten kenellekään käyttäjällä ei ole mitään kategorioita

8) Tekstikäyttöliittymä kaatuu kun yritän listata kategoriat. Toisaalta en tiedä onko tarkoitus toimia vielä, vaatimusmäärittelyssä ei sanota että tämän pitäisi toimia vielä joten ei välttämättä varsinaisesti ongelma

9) Tekstikäyttöliittymä kaatuu kun yritän luoda uuden käyttäjän.
 
10) Tekstikäyttöliittymä antaa valita tapahtumalle kategorian jota ei ole olemassa (ei sitten kuitenkaan ilmeisesti luo tapahtumaa).

11) Tekstikäyttöliittymä pyytää antamaan kategorian numeron, mutta ilmeisesti siihen pitääkin kirjoittaa kategorian nimi.

12) Vaatimusmäärittelyssä sanotaan että salasana täytyy asettaa kun luodaan uutta käyttäjää. Se kuitenkin hyväksyy tyhjän salasanan. En tiedä onko tarkoituksella mutta mainitsen kuitenkin.

**Comment by valtterikantanen** [comment]
Suuret kiitokset kattavasta palautteesta! Monet ongelmista liittyivät siihen, kun käytössä oli samaan aikaan sekä teksti- että graafinen käyttöliittymä. Nyt graafinen käyttöliittymä on saatettu ajan tasalle, ja ainakaan kertomiasi virheitä ei enää esiinny.

Tsemppiä loppukurssiin!
